# Generated by Django 3.0.8 on 2020-07-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_host_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='Phone_no',
            field=models.IntegerField(blank=True, default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='email_id',
            field=models.EmailField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='host_image',
            field=models.ImageField(blank=True, default='download.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='id_proof',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_image',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
