# Generated by Django 3.0.8 on 2020-07-26 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20200725_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='email_id',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
